url: https://www.leanjs.com   # with the https protocol
enforce_ssl: www.leanjs.com   # without any protocol
assets:
  compress:
    css: false
    js: false

  autowrite: true
  cache: .asset-cache
  cache_type: filesystem
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true

  sources:
    - _assets/css
    - _assets/img

  features:
    liquid: false
    integrity: false
    automatic_img_size: true
    automatic_img_alt : true